[package]
name = "hackrf-sys"
version = "0.1.0"
authors = ["rfdoell <rfdoell@users.noreply.github.com>"]

[dependencies]
log = "0.4"
clap = "2.23.0"
simple_logger = "1.0.1"

[build-dependencies]
bindgen = "0.40.0"
